MADNESS: cis.cpp File Reference
cis.cpp File Reference
#include <madness/chem/TDHF.h>
#include <madness/mra/commandlineparser.h>
#include <madness/misc/info.h>
#include <madness/world/worldmem.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::TDHF::analyze(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::TDHF::get_calc(), madness::TDHF::get_calcparam(), madness::TDHF::get_parameters(), madness::World::gop, madness::TDHF::help(), madness::initialize(), madness::commandlineparser::key_exists(), madness::TDHF::prepare_calculation(), madness::QCCalculationParametersBase::print(), madness::print(), madness::print_header1(), madness::print_header2(), madness::commandlineparser::print_map(), madness::print_meminfo(), madness::TDHF::print_parameters(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), madness::TDHF::solve_cis(), madness::startup(), madness::TDHF::test(), and madness::wall_time().