MADNESS: generate_frequency_answers.cpp File Reference
generate_frequency_answers.cpp File Reference
#include "ExcitedResponse.hpp"
#include "FrequencyResponse.hpp"
#include "ResponseExceptions.hpp"
#include "TDDFT.h"
#include "apps/chem/SCF.h"
#include "apps/external_headers/catch.hpp"
#include "apps/external_headers/tensor_json.hpp"
#include "madness/world/worldmem.h"
#include "response_functions.h"
#include "runners.hpp"
#include "string"
#include "timer.h"
#include "write_test_input.h"
#include "x_space.h"
#include "response_data_base.hpp"
Macros
#define CATCH_CONFIG_RUNNER
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Function Documentation
main()
int main (int argc, char * argv[])
References e(), madness::WorldGopInterface::fence(), madness::World::gop, madness::initialize(), madness::startup(), and xc.