MADNESS: mad-dft.cpp File Reference
mad-dft.cpp File Reference
#include <madness/misc/info.h>
#include "maddft/response_manager.hpp"
Typedefs
using path = std::filesystem::path
Functions
auto main (int argc, char *argv[]) -> int
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
auto main (int argc, char * argv[]) -> int
References SafeMPI::COMM_WORLD, e(), error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, help, madness::initialize(), print(), madness::print_header1(), madness::print_meminfo(), madness::info::print_revision_information(), print_stats(), madness::World::rank(), and madness::startup().