MADNESS: madqc.cpp File Reference
madqc.cpp File Reference
#include <fstream>
#include "madqc/calc_factory.hpp"
#include "madqc/calc_manager.hpp"
#include "madqc/parameter_manager.hpp"
#include <madness/misc/info.h>
#include <madness/world/worldmem.h>
Functions
static void END_TIMER (World &world, const char *msg)
int main (int argc, char **argv)
static void START_TIMER (World &world)
Variables
static double sss
static double ttt
Function Documentation
END_TIMER()
static void END_TIMER (World & world, const char * msg) static
References madness::cpu_time(), madness::World::rank(), sss, ttt, and madness::wall_time().
main()
int main (int argc, char ** argv)
References e(), madness::WorldGopInterface::fence(), madness::finalize(), madness::Tensor< T >::flat(), madness::Molecule::get_all_coords(), madness::World::gop, madness::initialize(), madness::commandlineparser::key_exists(), molecule, opt(), madness::print(), madness::print_header1(), madness::info::print_revision_information(), madness::print_stats(), madness::World::rank(), START_TIMER, and madness::startup().
START_TIMER()
static void START_TIMER (World & world) static
References madness::cpu_time(), madness::WorldGopInterface::fence(), madness::World::gop, sss, ttt, and madness::wall_time().
Variable Documentation
sss
double sss static
Referenced by END_TIMER(), and START_TIMER().
ttt
double ttt static
Referenced by END_TIMER(), and START_TIMER().