MADNESS: test_coordinator.cpp File Reference
test_coordinator.cpp File Reference
#include "CalculationParameters.h"
#include "FrequencyResponse.hpp"
#include "response_manager.hpp"
#include "madness/external/catch/catch.hpp"
#include "string"
#include <filesystem>
#include <utility>
Classes
struct CommandLineArgs
Macros
#define CATCH_CONFIG_RUNNER
Typedefs
using path = std::filesystem::path
Functions
std::pair< CalculationParameters, ResponseParameters > get_params (const std::string &json_input_path)
int main (int argc, char *argv[])
TEST_CASE ("Define parameters with input and mol file separately")
TEST_CASE ("Paramter Reader From input path", "[JSON]")
TEST_CASE ("Run MOLDFT + MOLRESPONSE")
TEST_CASE ("Run MOLDFT")
TEST_CASE ("Testing Parameters Class", "[Parameters]")
Variables
CommandLineArgs cmdArgs
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
get_params()
std::pair<CalculationParameters, ResponseParameters> get_params (const std::string & json_input_path)
main()
int main (int argc, char * argv[])
References cmdArgs, madness::initialize(), CommandLineArgs::parse(), and madness::startup().
TEST_CASE() [1/5]
TEST_CASE ("Define parameters with input and mol file separately")
References madness::World::get_default().
TEST_CASE() [2/5]
TEST_CASE ("Paramter Reader From input path" , "" [JSON])
References CHECK, cmdArgs, and madness::World::get_default().
TEST_CASE() [3/5]
TEST_CASE ("Run MOLDFT + MOLRESPONSE")
References madness::World::get_default().
TEST_CASE() [4/5]
TEST_CASE ("Run MOLDFT")
References madness::World::get_default().
TEST_CASE() [5/5]
TEST_CASE ("Testing Parameters Class" , "" [Parameters])
References CHECK, cmdArgs, madness::World::get_default(), madness::print(), madness::commandlineparser::set_defaults(), and madness::commandlineparser::value().
Variable Documentation
cmdArgs
CommandLineArgs cmdArgs
Referenced by main(), and TEST_CASE().