MADNESS: test_manager.cpp File Reference
test_manager.cpp File Reference
#include <filesystem>
#include "maddft/response_manager.hpp"
#include "madness/external/catch/catch.hpp"
#include "molresponse/FrequencyResponse.hpp"
Macros
#define CATCH_CONFIG_RUNNER
Typedefs
using path = std::filesystem::path
Functions
int main (int argc, char *argv[])
TEST_CASE ("Basic Input", "[Parameters]")
TEST_CASE ("Mixed Input")
TEST_CASE ("MOLDFT ONLY", "[Parameters]")
TEST_CASE ("Response Manager")
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
int main (int argc, char * argv[])
References madness::finalize(), madness::initialize(), and madness::startup().
TEST_CASE() [1/4]
TEST_CASE ("Basic Input" , "" [Parameters])
References diff(), and print().
TEST_CASE() [2/4]
TEST_CASE ("Mixed Input")
References diff(), and print().
TEST_CASE() [3/4]
TEST_CASE ("MOLDFT ONLY" , "" [Parameters])
References diff(), and print().
TEST_CASE() [4/4]
TEST_CASE ("Response Manager")
References print().