MADNESS: test_managers.cpp File Reference
test_managers.cpp File Reference
#include "calc_factory.hpp"
#include "calc_manager.hpp"
#include "madness/external/catch/catch.hpp"
#include "parameter_manager.hpp"
#include <filesystem>
Macros
#define CATCH_CONFIG_RUNNER
Typedefs
using path = std::filesystem::path
Functions
int main (int argc, char *argv[])
TEST_CASE ("Constructing an Optimization Calculation")
TEST_CASE ("Copy driver with new name... or nested")
TEST_CASE ("Hyperpolarizability Calculation")
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Typedef Documentation
path
using path = std::filesystem::path
Function Documentation
main()
int main (int argc, char * argv[])
References madness::initialize().
TEST_CASE() [1/3]
TEST_CASE ("Constructing an Optimization Calculation")
References e(), molecule, opt(), and print().
TEST_CASE() [2/3]
TEST_CASE ("Copy driver with new name... or nested")
References molecule, and print().
TEST_CASE() [3/3]
TEST_CASE ("Hyperpolarizability Calculation")